name: Deploy all communities

on:
  workflow_dispatch:
    inputs:
      dry-run:
        description: Don't publish packages to Thunderstore, upload build artifacts only
        required: false
        default: false
        type: boolean
  schedule:
    - cron: "0 0 * * *"

jobs:
  list-communities:
    name: List community configuration identifiers
    runs-on: ubuntu-latest
    outputs:
      communities: ${{ steps.list.outputs.communities }}
      community_secret_prefixes: ${{ steps.list.outputs.community_secret_prefixes }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: List communities
        id: list
        uses: ./.github/actions/listCommunities

  dispatch-community-deploys:
    name: Dispatch community deploys
    needs: list-communities
    if: ${{ needs.list-communities.outputs.communities != '[]' && needs.list-communities.outputs.communities != '' }}
    strategy:
      matrix:
        community: ${{ fromJson(needs.list-communities.outputs.communities) }}
      fail-fast: false
    uses: ./.github/workflows/deployCommunity.yml
    with:
      community: ${{ matrix.community }}
      community_secret_prefix: ${{ fromJson(needs.list-communities.outputs.community_secret_prefixes)[matrix.community] }}
      dry-run: ${{ inputs.dry-run == true || inputs.dry-run == 'true' }}
    permissions:
      contents: write
      pull-requests: write
    secrets: inherit
