name: Deploy all communities

on:
  workflow_dispatch: 
  schedule:
    - cron: "0 0 * * *"

jobs:
  list-communities:
    name: List community configuration identifiers
    runs-on: ubuntu-latest
    outputs: 
      communities: ${{ steps.list.outputs.communities }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
    
      - name: List communities
        id: list
        uses: .github/actions/listCommunities

  dispatch-game-update-checks:
    needs: list-communities
    if: ${{ needs.list-communities.outputs.communities != '[]' && needs.list-communities.outputs.communities != '' }}
    strategy: 
      matrix:
        community: ${{ needs.list-communities.outputs.communities }}
      fail-fast: false
    uses: .github/workflows/deployCommunity.yml
    with:
      community: ${{ matrix.community }}
    permissions:
      contents: write
      pull-requests: write
    secrets: inherit
      