name: Deploy community

on:
  workflow_dispatch:
    inputs:
      community:
        description: Base name of file in 'Communities' directory
        required: true
        type: string
      community_secret_prefix:
        description: Prefix for names of secrets corresponding to the community configuration
        required: true
        type: string
      dry-run:
        description: Don't publish packages to Thunderstore, upload build artifact only
        required: false
        default: false
        type: boolean
  workflow_call:
    inputs:
      community:
        required: true
        type: string
      community_secret_prefix:
        required: true
        type: string
      dry-run:
        required: false
        default: false
        type: boolean

jobs:
  deploy:
    name: Run 'build' project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          filter: tree:0

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Build
        if: ${{ inputs.dry-run == true || inputs.dry-run == "true" }}
        env:
          THUNDERSTORE_API_TOKEN: ${{ secrets[format('{0}_THUNDERSTORE_API_TOKEN', inputs.community_secret_prefix)] }}
        run: |
          ./build.sh --community ${{ inputs.community }}

      - name: Build & Publish
        if: ${{ inputs.dry-run != true && inputs.dry-run != "true" }}
        env:
          THUNDERSTORE_API_TOKEN: ${{ secrets[format('{0}_THUNDERSTORE_API_TOKEN', inputs.community_secret_prefix)] }}
        run: |
          ./build.sh --target "Publish built Thunderstore packages" --community ${{ inputs.community }}

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ inputs.community }}
          path: "build/dist/*.zip"
